import 'package:compound_widgets/compound_widgets.dart';
import 'package:flutter/material.dart';

class AppListContentProvider {
  // Generated mocked AppItems from the design. Substitute it with TV content provider.
  static final List<AppItem> children = [
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/prime.png",
      appTitle: '''prime''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/coupang.png",
      appTitle: '''coupang''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/disney.png",
      appTitle: '''disney''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/lgfit.png",
      appTitle: '''lgfit''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/netflix.png",
      appTitle: '''netflix''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/tving.png",
      appTitle: '''tving''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/wavve.png",
      appTitle: '''wavve''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/youtube.png",
      appTitle: '''youtube''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/prime.png",
      appTitle: '''prime''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/coupang.png",
      appTitle: '''coupang''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/disney.png",
      appTitle: '''disney''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/lgfit.png",
      appTitle: '''lgfit''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/netflix.png",
      appTitle: '''netflix''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/tving.png",
      appTitle: '''tving''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/wavve.png",
      appTitle: '''wavve''',
      backgroundColor: Color(0x00000000),
    ),
    const AppItem(
      itemWidth: 360.0,
      itemHeight: 336.0,
      imageWidth: 252.0,
      imageHeight: 252.0,
      url: "assets/generated_drawables/youtube.png",
      appTitle: '''youtube''',
      backgroundColor: Color(0x00000000),
    )
  ];

  const AppListContentProvider();
}
